#  ======================================
#  World of Warcraft
#  Character + Guild Database
#  ======================================
#  Format:
#  Character name*: Must be between 2-12 characters long. Accented characters are supported. Mixed capitals, spaces, numbers and symbols are not supported.
#  Guild name*: Must be between 2-24 characters long. Accented characters, mixed capitals and spaces are supported. Numbers and symbols are not supported.
#  (*) must be unique within a given realm
#  Colon : separates fields for each guild
#  Pipe | separates field values
#  ======================================
#  Profile and Character DDLs are the only two 'functioning' DDLs in 'Viewer', but all are in 'Editor'
#  Character Name associated with Profile Name
#  Each subsequent DDL is populated based upon prior DDL [specialization -> class -> race -> faction]
#  Click-to-Edit fields: instead of DDLs, use LISTBOXes instead.
#  [Click-to-Edit fields: Level, Guild, Specialization, Profession1+2]
#  RealmURL is a copy of 'Realm' names with any spaces or single apostrophes replaced with hypens
#  Blizzard URL = Button = link's construction = baseurl + /realmURL + /charactername
#  ======================================

[templates]
gui_fields=profile|character|level|guild {+ is leader? [*]}|gender|realm|faction|race|class|specialization|armor {type}|profession1|profession2|profession3|profession4|profession5|blizzard url
guild data=guild name1:realm:faction:guild leader|guild name2:realm:faction:guild leader
blizzard url=https://worldofwarcraft.blizzard.com/en-us/character/us/realmurl/charactername/
notations:Realm URL has its own ini section entry [Realms]-realmurl for use in the above template format

[Guild Names]
name=Deyhide|Friends of Elphaba|Instant Mashed Opponents|Random Acts of Rodenticide|Running With Scissors
realm=Shadowsong
leader=EarcenCovene|Garaharm|Sumula|Talyka|Zoerunah
data=Deyhide:Shadowsong:Horde:Talyka|Friends of Elphaba:Shadowsong:Alliance:EarcenCovene|Instant Mashed Opponents:Shadowsong:Horde:Garaharm|Random Acts of Rodenticide:Shadowsong:Horde:Zoerunah|Running With Scissors:Shadowsong:Horde:Sumula
limitations=Must be between 2-24 characters long. Accented characters, mixed capitals and spaces are supported. Numbers and symbols are not supported.
notations='Random Acts of Rodenticide' is 26 characters + spaces in length, but appears valid (is grandfathered in?)

[Profile Names]
profile name=PEN|PENalt

[Character Names]
limitations=Must be between 2-12 characters long. Accented characters are supported. Mixed capitals, spaces, numbers and symbols are not supported.

[PEN's Character Names]
character name=ChaoticSeer|MithrasBane|EarcenCovene|Garaharm|Sumula|Talyka|Zoerunah

[PENalt's Character Names]
character name=CharacterC

[ChaoticSeer]
character name=ChaoticSeer
level=80
faction=Horde
race=Tauren
class=Druid
specialization=Balance
armor type=Leather
gender=Male
profession1=Leather Worker
profession2=Skinning
profession3=Cooking
profession4=Fishing
profession5=Archealogy
guild=Running With Scissors
realm url=shadowsong
blizzard url=https://worldofwarcraft.blizzard.com/en-us/character/us/shadowsong/chaoticseer/

[MithrasBane]
character name=MithrasBane
level=70
faction=Horde
race=Undead
class=Warlock
specialization=Demonologist
armor type=Cloth
gender=Male
profession1=Tailor
profession2=Herbalism
profession3=Cooking
profession4=Fishing
profession5=Archeology
guild=Running With Scissors
realm url=shadowsong
blizzard url=https://worldofwarcraft.blizzard.com/en-us/character/us/shadowsong/mithrasbane/

[CharacterC]
character name=CharacterC
level=44
faction=Alliance
race=Orc
class=Shaman
specialization=Elemental [Ranged]
armor type=Mail
gender=Male
profession1=Engineering
profession2=Mining
profession3=Cooking
profession4=Fishing
profession5=
guild=ourguild2
realm url=shadowsong
blizzard url=https://worldofwarcraft.blizzard.com/en-us/character/us/shadowsong/characterc/
