#  ======================================
#  World of Warcraft - User Identity Map
#  Local machine only - do not distribute
#  ======================================
#  xx Format : WinLoginID:Profile1;Profile2;Profile3
#  xx Colon : separates windows login ID from profile name(s).
#  xx Semicolon ; separates profile name(s) for current user
#  ======================================
#  Format : win login name = profile name1|profile name2|etc.
#  ======================================

[Profiles]
pen=PEN|PENalt
